clone:
  tags: true
build:
  image: golang:1.5
  pull: true
  commands:
    - go get golang.org/x/tools/cmd/vet
    - go get golang.org/x/tools/cmd/goimports
    - go get
    - make all
    - govc/build.sh

